info/urls.py
from django.urls import path
from . import views
app_name = 'info'
urlpatterns = [
    path('', views.home, name='index'),
    path('about/', views.about, name='about'),
]

myproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from os import getenv

urlpatterns = [
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),  # Dil dəyişdirmək üçün URL
]

# Dil prefiksi ilə URL-ləri avtomaatik olaraq əlavə edir
urlpatterns += i18n_patterns(
    path('', include('info.urls')),
    path('', include('contact.urls')),
    path('', include('services.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/models.py
# models.py
from django.db import models

class Slider(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='slider_images/')

    def __str__(self):
        return self.title



class HomeService(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='service_images/', blank=True, null=True)  # Şəkil sahəsi

    def __str__(self):
        return self.title

class About(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image_one = models.ImageField(upload_to='about_images/', blank=True, null=True)
    image_two = models.ImageField(upload_to='about_images/', blank=True, null=True)

    def __str__(self):
        return self.title

from django.db import models

class Counter(models.Model):
    number = models.PositiveIntegerField()
    suffix = models.CharField(max_length=10, blank=True, null=True)  
    label = models.CharField(max_length=100)  
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.description


from django.db import models

class CoreFeature(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    num = models.PositiveIntegerField()  
    
    def __str__(self):
        return self.title


class CoreFeatureVideo(models.Model):
    video_file = models.FileField(upload_to='videos/')  
    thumbnail = models.ImageField(upload_to='images/', blank=True, null=True) 

    def __str__(self):
        return f"Video {self.id}"

class CoreFeatureSection(models.Model):
    title = models.CharField(max_length=255) 
    subtitle = models.CharField(max_length=255)  

    def __str__(self):
        return self.title



class RenovationInfo(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    background_image = models.ImageField(upload_to='background_images/')
    circle_image = models.ImageField(upload_to='circle_images/')

    def __str__(self):
        return self.title

class ClientReview(models.Model):
    section_header = models.CharField(max_length=255,)
    reviews_header = models.CharField(max_length=255,)
    
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    review = models.TextField()
    image = models.ImageField(upload_to='client_review_images/', blank=True, null=True)  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.name}"


# ++++++++++++++++++++++ABOUT+++++++++++++++++++++++++++++++

class AboutUs(models.Model):
    title = models.CharField(max_length=255)  # Başlıq
    description = models.TextField()         # Təsvir
    breadcrumb_title = models.CharField(max_length=255, default="About Us") 
    breadcrumb_home = models.CharField(max_length=255, default="Home")      
    background_image = models.ImageField(upload_to='backgrounds/', default='backgrounds/default.png')  

    class Meta:
        verbose_name = "About (About seifesi 1 )"  
        verbose_name_plural = "About (About seifesi 1)"  

    def __str__(self):
        return self.title


class AboutSection(models.Model):
    main_heading = models.CharField(max_length=255)
    who_we_are_text = models.TextField()
    who_we_are_image = models.ImageField(upload_to='about_images/')
    whats_in_it_for_me_title = models.CharField(max_length=255)
    whats_in_it_for_me_points = models.JSONField()  
    whats_in_it_for_me_image = models.ImageField(upload_to='about_images/')
    
    def __str__(self):
        return self.main_heading

    class Meta:
        verbose_name = "About seifesi 2"
        verbose_name_plural = "About seifesi 2"


class HowItWorks(models.Model):
    background_image = models.ImageField(upload_to='how_it_works/', blank=True, null=True)  # Background şəkli
    heading_text = models.CharField(max_length=255, default="Plan + Control")  # Başlıq üçün alt yazı
    heading_title = models.CharField(max_length=255, default="How it Works")  # Başlıq mətn

    step_1_title = models.CharField(max_length=255, default="Phase Plan")
    step_1_description = models.TextField(default="This step connects the design process and its milestones with construction.")

    step_2_title = models.CharField(max_length=255, default="Design Pull Plan")
    step_2_description = models.TextField(default="We work with the design team to establish a detailed plan for reaching our goals.")

    step_3_title = models.CharField(max_length=255, default="Coordinated Layout")
    step_3_description = models.TextField(default="This process creates a single point of truth: drawings all project.")

    step_4_title = models.CharField(max_length=255, default="Quality Control")
    step_4_description = models.TextField(default="Having geometry worked out in the Layout step, prior to construction.")

    

    class Meta:
        verbose_name = "About seifesi 3"
        verbose_name_plural = "About seifesi 3"

    def __str__(self):
        return "How It Works Settings"

info/views.py
from django.shortcuts import render
from .models import *

from django.shortcuts import render
from .models import *


def home(request):
    sliders = Slider.objects.all()
    services = HomeService.objects.all()
    counters = Counter.objects.all()
    features = CoreFeature.objects.all().order_by('num')
    video = CoreFeatureVideo.objects.first()
    about_info = About.objects.first()
    section_info = CoreFeatureSection.objects.first()
    renovation_info = RenovationInfo.objects.first()

    return render(request, 'index.html', {
        'sliders': sliders,
        'services': services,
        'about_info': about_info,
        'counters': counters,
        'features': features,
        'video': video,
        'section_info': section_info,
        'renovation_info': renovation_info,
    })


def about(request):
    about_data = AboutUs.objects.first() 
    counters = Counter.objects.all()
    data = HowItWorks.objects.first()
    renovation_info = RenovationInfo.objects.first()
    about_section = AboutSection.objects.first() 
    context = {
        'about': about_data ,
        'counters': counters,
        'data': data, 
        'renovation_info': renovation_info,
        'about_section': about_section, 
    }
    return render(request, 'about.html', context)

info/templates/about.html
{% extends "layout.html" %}

{% load static %}


{% block main %}




    <!-- Banner Style One Start -->
<section class="banner-style-one">
    <div class="parallax" style="background-image: url('{{ about.background_image.url }}');"></div>
    <div class="container">
        <div class="row">
            <div class="banner-details">
                <h2>{{ about.title }}</h2>
                <p>{{ about.description }}</p>
            </div>
        </div>
    </div>
    <div class="breadcrums">
        <div class="container">
            <div class="row">
                <ul>
                    <li>
                        <a href="{% url 'info:index' %}">
                            <i class="fa-solid fa-house"></i>
                            <p>ss</p>
                        </a>
                    </li>
                    <li class="current">
                        <p>ss</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

    
    <!-- Banner Style One End -->

    <!-- About-First Start -->
    <section class="gap about-first">
        <div class="container">
            <div class="row">
                <h2>{{ about_section.main_heading }}</h2>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="who-we-are">
                        <div>
                            <h3 style="font-size: 24px; line-height: 1.5; max-width: 800px; margin: 0 auto; padding: 20px; text-align: left; word-wrap: break-word; white-space: normal;">
                                {{ about_section.who_we_are_text }}
                            </h3>
                            
                        </div>
                        <figure>
                            <img class="w-100" src="{{ about_section.who_we_are_image.url }}" alt="About Image One" 
                            style="width: 100%; border-radius: 15px; object-fit: cover;">
                        
                        </figure>
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-1">
                    <div class="who-we-are space">
                        <div>
                            <h3>{{ about_section.whats_in_it_for_me_title }}</h3>
                            <ul>
                                {% for point in about_section.whats_in_it_for_me_points %}
                                    <li><i class="fa-solid fa-circle-dot"></i> {{ point }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <figure>
                            <img class="w-100" src="{{ about_section.whats_in_it_for_me_image.url }}" alt="About Image Two" 
    style="width: 100%; border-radius: 15px; object-fit: cover;">

                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- About-First End -->

    <!-- Counter Style One Start -->
    <section class="gap no-top counter-style-one">
        <div class="container">
            <div class="row">
                {% for counter in counters %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="counter-data {% if forloop.counter|divisibleby:2 %}upper-space{% endif %}">
                        <div class="count">
                            <span class="counter">{{ counter.number }}</span>{{ counter.suffix }}
                            <i>{{ counter.label }}</i>
                        </div>
                        <h4>{{ counter.description }}</h4>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Counter Style One End -->

    <section 
     class="gap about-how-it-works light-bg-color" 
        style="background-image: url('{{ data.background_image.url }}'); background-size: cover; background-repeat: no-repeat; background-position: center;">
     <div class="heading">
      
        <span style="color: white;">{{ data.heading_text }}</span>
        <h2 style="color: white;">{{ data.heading_title }}</h2>

       </div>
        <div class="container">
        <div class="row g-0">
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="plans">
                    <div class="y-box d-flex-all">1.</div>
                    <h3>{{ data.step_1_title }}</h3>
                    <p>{{ data.step_1_description }}</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="plans">
                    <div class="y-box d-flex-all">2.</div>
                    <h3>{{ data.step_2_title }}</h3>
                    <p>{{ data.step_2_description }}</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="plans">
                    <div class="y-box d-flex-all">3.</div>
                    <h3>{{ data.step_3_title }}</h3>
                    <p>{{ data.step_3_description }}</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="plans">
                    <div class="y-box d-flex-all">4.</div>
                    <h3>{{ data.step_4_title }}</h3>
                    <p>{{ data.step_4_description }}</p>
                </div>
            </div>
        </div>
    </div>
</section>

    
    
    
    <!--About How It Works End -->



    <!-- Renovation Start -->
    <section class="gap renovation">    
        <!-- Background Image -->
        <div class="parallax" style="background-image: url({{ renovation_info.background_image.url }}); height: 500px; background-size: cover; background-position: center;"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="reno-data">
                        <!-- Title -->
                        <h3>{{ renovation_info.title }}</h3>
                        <!-- Description -->
                        <p>{{ renovation_info.description }}</p>
                        <!-- Circle Image -->
                        <div class="bbtn">
                            <figure>
                                <img class="w-auto circle-layer" src="{{ renovation_info.circle_image.url }}" alt="Circle Text" style="width: 70px; height: 70px; border-radius: 10%; border: 2px solid #fff;">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> 
    <!-- Renovation End -->

    

{% endblock main %}
    

info/templates/index.html
{% extends "layout.html" %}

{% load static %}


{% block main %}


<!-- Featured Slider One End -->
<section class="featured-slider-one" style="background: grey;">
    <div class="containe">
        <div class="ro f-slider-one owl-carousel">
            {% for slider in sliders %}
                <div class="f-slider-layer">
                    <img src="{{ slider.image.url }}" alt="{{ slider.title }}" style="width: 100%; height: 100%; object-fit: cover;">
                    <div class="f-slider-one-data">
                        <h1>{{ slider.title }}</h1>
                        <p>{{ slider.description }}</p>
                       
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>


<!-- Service Style One Start -->
<section class="gap service-style-one">
    <div class="container">
        <div class="row">
            {% for service in services %}
                <div class="col-lg-4 col-md-6 col-sm-12 text-center">
                    <div class="service-data">
                        <div class="svg-icon d-flex-all">
                            {% if service.image %}
                            <img src="{{ service.image.url }}" alt="{{ service.title }}" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover;">
                            {% endif %}
                        </div>
                        <h3><a>{{ service.title }}</a></h3>
                        <p>{{ service.description }}</p>
                        
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>


<!-- Service Style Two End -->

<!-- About Style One Start -->
<section class="gap no-top about-style-one">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="about-data-left">
                    <figure>
                        <img src="{{ about_info.image_one.url }}" alt="About One" style="border-radius: 20px; max-width: 100%; height: auto; display: block; margin-bottom: 20px;">
                    </figure>
                    <figure class="about-image">
                        <img src="{{ about_info.image_two.url }}" alt="About Two" style="border-radius: 20px; max-width: 100%; height: auto; display: block;">
                    </figure>
                    
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-data-right">
                    <h2>{{ about_info.title }}</h2>
                    <div class="about-info">
                        <p>{{ about_info.description }}</p>
                        
                        {% if about_info.signature %}
                        <figure>
                            <img src="{{ about_info.signature.url }}" alt="Signature">
                        </figure>
                        {% endif %}
                        
                        <h3>{{ about_info.director_name }}</h3>
                        <h4>{{ about_info.director_title }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- About Style One End -->

<!-- Counter Style One Start -->
<section class="gap no-top counter-style-one">
    <div class="container">
        <div class="row">
            {% for counter in counters %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="counter-data {% if forloop.counter|divisibleby:2 %}upper-space{% endif %}">
                    <div class="count">
                        <span class="counter">{{ counter.number }}</span>{{ counter.suffix }}
                        <i>{{ counter.label }}</i>
                    </div>
                    <h4>{{ counter.description }}</h4>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<!-- Counter Style One End -->



<!-- Core Features Start -->
<section class="core-features">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="space">
                    <div class="heading-style-2">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="data">
                                        <span>{{ section_info.title }}</span> 
                                        <h2>{{ section_info.subtitle }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion" id="accordionExample">
                        {% for feature in features %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ feature.num }}">
                                <button class="accordion-button {% if not forloop.first %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ feature.num }}" aria-expanded="{{ forloop.first }}" aria-controls="collapse{{ feature.num }}">
                                    <span class="num">{{ feature.num|add:"0" }}.</span> {{ feature.title }}
                                </button>
                            </h2>
                            <div id="collapse{{ feature.num }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading{{ feature.num }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>{{ feature.description }}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shape">
                    <div class="video">
                        <figure>
                            <img src="{{ video.thumbnail.url }}" alt="Core Feature Img">
                        </figure>
                        <a class="video-play-btn" data-fancybox="video" href="{{ video.video_file.url }}">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="35" height="56" viewBox="0 0 35 56">
                                <defs>
                                    <clipPath id="clip-video_arrow">
                                        <rect width="35" height="56"/>
                                    </clipPath>
                                </defs>
                                <g id="video_arrow" data-name="video arrow" clip-path="url(#clip-video_arrow)">
                                    <path id="Shape_1" data-name="Shape 1" d="M1362,5000.8,1327,4972V5027Z" transform="translate(-1326.998 -4971.996)" fill="rgba(0,0,0,0)"/>
                                    <path id="Shape_1_-_Outline" data-name="Shape 1 - Outline" d="M1333,5015.017l19.29-14.437L1333,4984.7v30.313M1327,5027V4972l35,28.807Z" transform="translate(-1326.998 -4971.996)"/>
                                </g>
                            </svg>
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Core Features End -->






<!-- Client Style One End -->

<!-- Renovation Start -->
<section class="gap renovation">    
    <!-- Background Image -->
    <div class="parallax" style="background-image: url({{ renovation_info.background_image.url }}); height: 500px; background-size: cover; background-position: center;"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="reno-data">
                    <!-- Title -->
                    <h3>{{ renovation_info.title }}</h3>
                    <!-- Description -->
                    <p>{{ renovation_info.description }}</p>
                    <!-- Circle Image -->
                    <div class="bbtn">
                        <figure>
                            <img class="w-auto circle-layer" src="{{ renovation_info.circle_image.url }}" alt="Circle Text" style="width: 70px; height: 70px; border-radius: 10%; border: 2px solid #fff;">
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Renovation End -->






{% endblock main %}




   